# octonion_ffa.py
# ============================================================================
# Octonionic Functional Fractal Automaton (OFFA).  A serious synthesis of three
# threads with the octonion representation:
#   * Wolfram CA          -- one local rule, evolved (octonion_wolfram).
#   * Fractal/substitution -- one rewrite, recursed -> self-similarity (octonion_fractal).
#   * EML "all computation" -- one operator + composition -> functional completeness.
#
# A substitution system sigma : grid -> grid expands every cell into an a×b block.
# octonion_fractal used only a LITERAL block (constant stamp, or the input itself, or
# a recolour).  OFFA makes the block a FUNCTIONAL of the cell: per colour the block is
# one of  { constant fill, the input g, a DIHEDRAL d(g), a recolour(g) }  -- the
# dihedral case is the new expressivity, giving kaleidoscopic / mirror-symmetric
# fractals (the Rule-90 / Sierpinski family of self-similar reflections).  And the map
# is applied RECURSIVELY (nested depth k): each level stamps the CURRENT grid, so the
# output is self-similar across scales -- "everything's computation" as one functional
# rule iterated fractally.  The colour->function table is learned from the task's own
# pairs and accepted only on EXACT reproduction.  Gradient-free, un-named.
#
# Octonionic reading: each block is the image of g under an element of the group
# generated by the dihedral D4 action and the colour (Fano) relabelling -- the same
# octonionic symmetry algebra used throughout -- selected per coarse cell by its
# colour.  The recursion is the functional power sigma^k.
# ============================================================================
import json, time, sys
import numpy as np
from octonion_arc import A, eq, DIHEDRAL

DIH = list(DIHEDRAL.values())

def _depth_ratio(Hi, Wi, Ho, Wo):
    """Return (a, b, k): block grid a×b applied k times gives (Ho,Wo) from (Hi,Wi).
    k=1 is a plain substitution; k>1 is a nested (self-similar) fractal."""
    if Hi == 0 or Wi == 0: return None
    # plain: Ho=a*Hi, Wo=b*Wi
    if Ho % Hi == 0 and Wo % Wi == 0:
        a, b = Ho // Hi, Wo // Wi
        if a >= 1 and b >= 1 and a * b >= 2: return (a, b, 1)
    # nested self-fractal with block grid = input shape: Ho=Hi^(k+1)? generalised by repeated *Hi
    r, c, k = Hi, Wi, 0
    while r < Ho and c < Wo and k < 4:
        r *= Hi; c *= Wi; k += 1
        if r == Ho and c == Wo and k >= 1: return (Hi, Wi, k + 0)  # each level: ×(Hi,Wi)
    return None

def _colormap(src, dst):
    if src.shape != dst.shape: return None
    cm = {}
    for x, y in zip(src.ravel().tolist(), dst.ravel().tolist()):
        if cm.get(x, y) != y: return None
        cm[x] = y
    return cm

def _classify_block(blk, g):
    """Identify how block was produced from g: ('fill',v) | ('id',) | ('dih',d) |
    ('recol',cm).  Returns a set of compatible specs (may be several)."""
    specs = []
    u = set(blk.ravel().tolist())
    if len(u) == 1: specs.append(("fill", u.pop()))
    if blk.shape == g.shape:
        if np.array_equal(blk, g): specs.append(("id",))
        for di, d in enumerate(DIH):
            dg = d(g)
            if dg.shape == blk.shape and np.array_equal(dg, blk): specs.append(("dih", di))
        cm = _colormap(g, blk)
        if cm is not None and any(k != v for k, v in cm.items()): specs.append(("recol", tuple(sorted(cm.items()))))
    return specs

def _apply_spec(spec, g):
    if spec[0] == "fill": return np.full(g.shape, spec[1], int)
    if spec[0] == "id": return A(g)
    if spec[0] == "dih": return A(DIH[spec[1]](A(g)))
    if spec[0] == "recol":
        cm = dict(spec[1]); return np.vectorize(lambda x: cm.get(int(x), int(x)))(A(g))
    return None

def _one_level(g, rule, a, b):
    g = A(g); H, W = g.shape; out = np.zeros((a * H, b * W), int)
    for r in range(H):
        for c in range(W):
            spec = rule.get(int(g[r, c]))
            if spec is None: return None
            blk = _apply_spec(spec, g)
            if blk is None or blk.shape != (H, W) and spec[0] != "fill":
                blk = np.full((H, W), 0, int) if spec[0] != "fill" else np.full((H, W), spec[1], int)
            out[r * H:(r + 1) * H, c * W:(c + 1) * W] = blk
    return out

def _learn(pairs, a, b, k):
    """Learn colour->functional-block consistent across all pairs (single level; for
    nested k>1 the same rule is reused at every level)."""
    rule = {}
    for gi, go in pairs:
        gi = A(gi); go = A(go)
        if k == 1:
            H, W = gi.shape
            if go.shape != (a * H, b * W): return None
            for r in range(H):
                for c in range(W):
                    blk = go[r * H:(r + 1) * H, c * W:(c + 1) * W]
                    specs = _classify_block(blk, gi)
                    col = int(gi[r, c])
                    if col in rule:
                        rule[col] = [s for s in rule[col] if s in specs]
                        if not rule[col]: return None
                    else:
                        if not specs: return None
                        rule[col] = specs
    return {c: ss[0] for c, ss in rule.items()} if rule else None

def _run(g, rule, a, b, k):
    g = A(g)
    for _ in range(k):
        g = _one_level(g, rule, a, b)
        if g is None: return None
    return g

def solve(task):
    pairs = [(A(p["input"]), A(p["output"])) for p in task["train"]]
    tests = [A(tp["input"]) for tp in task["test"]]
    Hi, Wi = pairs[0][0].shape; Ho, Wo = pairs[0][1].shape
    dr = _depth_ratio(Hi, Wi, Ho, Wo)
    if dr is None: return None
    a, b, k = dr
    if k > 1: a, b = Hi, Wi                                   # nested: block grid = input shape each level
    rule = _learn(pairs, a, b, 1)                            # rule learned at level-1 granularity
    if rule is None: return None
    for i, o in pairs:
        r = _run(i, rule, a, b, k)
        if r is None or not eq(r, o): return None
    pr = [_run(t, rule, a, b, k) for t in tests]
    if any(p is None for p in pr): return None
    return [A(p) for p in pr]


if __name__ == "__main__":
    DIR = "arc_data/"; split = sys.argv[1] if len(sys.argv) > 1 else "training"
    ch = json.load(open(DIR + "arc-agi_%s_challenges.json" % split))
    sol = json.load(open(DIR + "arc-agi_%s_solutions.json" % split))
    t0 = time.time(); solved = []
    for tid, task in ch.items():
        try: pr = solve(task)
        except Exception: pr = None
        if pr and all(eq(pr[i], A(g)) for i, g in enumerate(sol[tid])): solved.append(tid)
    print("OFFA (octonionic functional fractal automaton, gradient-free): %d / %d  %s  (%.0fs)"
          % (len(solved), len(ch), split, time.time() - t0))
    open("/tmp/ffa_%s.ids" % split, "w").write(" ".join(solved))
